In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.9.1'

In [3]:
dataset = pd.read_csv(r'C:\Users\pj\Documents\ML_NEW\data for ml\Churn_Modelling.csv')
X = dataset.iloc[:,3:-1].values
y = dataset.iloc[:,-1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2] = le.fit_transform(X[:,2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


### One hot encoding

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[1])],remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

### building ann 

In [13]:
ann = tf.keras.models.Sequential()

### ADDING INPUT AND HIDDEN LAYER

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation = 'relu'))

### SECOND HIDDEN LAYER

In [18]:
ann.add(tf.keras.layers.Dense(units=6,activation = 'relu'))

### output layer

In [19]:
ann.add(tf.keras.layers.Dense(units=1,activation = 'sigmoid'))

### Training  the ann

In [20]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [22]:
ann.fit(X_train,y_train, batch_size = 32,epochs = 100)

Epoch 1/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4637 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 1s 6ms/step - loss: 0.4456 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4360 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 2s 8ms/step - loss: 0.4314 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4284 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4262 - accuracy: 0.8010
Epoch 7/100
250/250 [==============================] - 2s 7ms/step - loss: 0.4243 - accuracy: 0.8131
Epoch 8/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4229 - accuracy: 0.8150
Epoch 9/100
250/250 [==============================] - 2s 6ms/step - loss: 0.4212 - accuracy: 0.8167
Epoch 10/100
250/250 [==============================] - 1s 5ms/step - loss: 0.4199 - accura

In [26]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 326ms/step
[[False]]


In [27]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 4ms/step
[[0 0]
 [1 1]
 [0 1]
 ...
 [0 1]
 [0 0]
 [0 0]]


In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1549   46]
 [ 258  147]]


0.848